services:
  app:
    build:
      context: .
      target: runner
    container_name: ethiopian-heritage-blog-prod
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/Blog
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    restart: always
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: ethiopian-heritage-blog-db-prod
    volumes:
      - mongodb_data_prod:/data/db
    restart: always

volumes:
  mongodb_data_prod:
