services:
  app:
    image: mahtot21/ethiopian-heritage-blog:latest
    container_name: ethiopian-heritage-blog-prod
    ports:
      - "80:3000"
    env_file: .env
    environment:
      - NODE_ENV=production
    restart: always
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: ethiopian-heritage-blog-db-prod
    volumes:
      - mongodb_data_prod:/data/db
    restart: always

volumes:
  mongodb_data_prod:
